"""Generate latex/tables/definitional-approaches.tex from moratorium-analysis.json.

Horizontal pgfplots bar chart of definitional approaches in moratorium
instruments. Categories: No Definition, Functional, Bundled, Size Threshold.
Percentages computed against `total_records` in the analysis JSON.
"""

from __future__ import annotations

from ._common import TABLES_DIR, load_analysis


LABELS = {
    "none": "No Definition",
    "functional": "Functional",
    "bundled": "Bundled",
    "size_threshold": "Size Threshold",
}

ORDER = ["size_threshold", "bundled", "functional", "none"]  # bottom-to-top


def render() -> str:
    a = load_analysis()
    total = a["total_records"]
    approaches = a["clause_prevalence"].get("definition_approaches", {})

    pairs = []
    for key in ORDER:
        count = approaches.get(key, 0)
        pct = (count / total) * 100 if total else 0.0
        pairs.append((LABELS[key], pct))

    states_csv = ",\n        ".join(label for label, _ in pairs)
    coords = " ".join(f"({pct:.1f},{label})" for label, pct in pairs)
    xmax = ((max(p for _, p in pairs) // 10) + 2) * 10

    return f"""% Auto-generated by scripts/generate_tables/definitional_approaches.py
% Source: research/analysis/moratorium-analysis.json
\\begin{{figure}}[htbp]
\\centering
\\caption{{Definitional Approaches in Moratorium Instruments}}
\\label{{tab:definitional-approaches}}
\\begin{{tikzpicture}}
\\begin{{axis}}[
    xbar,
    bar width=16pt,
    width=0.8\\textwidth,
    height=6cm,
    xlabel={{Percentage of Instruments}},
    xmin=0,
    xmax={xmax:.0f},
    ytick=data,
    symbolic y coords={{
        {states_csv}
    }},
    nodes near coords={{\\pgfmathprintnumber\\pgfplotspointmeta\\%}},
    nodes near coords style={{font=\\small\\bfseries, anchor=west, color=black}},
    every axis plot/.append style={{fill=chart-bar, draw=chart-bar-dark}},
    axis lines*=left,
    xmajorgrids=true,
    grid style={{gray!20}},
    tick label style={{font=\\small}},
    label style={{font=\\small}},
    y dir=normal,
]
\\addplot[fill=chart-bar, draw=chart-bar-dark] coordinates {{
    {coords}
}};
\\end{{axis}}
\\end{{tikzpicture}}
\\begin{{flushleft}}
\\small\\textit{{Note:}} Based on $n = {total}$ structured extractions.
``Functional'' definitions describe the regulated use by its
characteristics (e.g., power consumption, cooling requirements).
``Bundled'' definitions combine data centers with related uses
such as cryptocurrency mining or AI computing facilities.
``Size threshold'' definitions apply only above a specified
square footage, power draw, or similar metric.
\\end{{flushleft}}
\\end{{figure}}
"""


def main():
    out = TABLES_DIR / "definitional-approaches.tex"
    out.write_text(render())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
