"""Generate latex/tables/findings-impact.tex from moratorium-analysis.json.

Two side-by-side subtables:
  (a) Findings detail level (Detailed / Moderate / Minimal / Absent)
  (b) Impact categories cited in legislative findings, sorted by frequency.

Both percentages are computed against `total_records` in the analysis JSON.
"""

from __future__ import annotations

from ._common import TABLES_DIR, load_analysis


# Pretty-print labels for impact categories — keys come from the JSON snake_case
IMPACT_LABELS = {
    "energy_grid": "Energy/Grid",
    "environmental": "Environmental",
    "economic_fiscal": "Economic/Fiscal",
    "land_use_compatibility": "Land Use Compatibility",
    "water": "Water Resources",
    "public_safety": "Public Safety",
    "noise": "Noise",
    "infrastructure": "Infrastructure",
    "air_quality": "Air Quality",
    "visual_aesthetic": "Visual/Aesthetic",
    "traffic_transportation": "Traffic/Transportation",
    "property_values": "Property Values",
}

DETAIL_ORDER = ["moderate", "minimal", "detailed", "absent"]
DETAIL_LABELS = {
    "moderate": "Moderate",
    "minimal": "Minimal",
    "detailed": "Detailed",
    "absent": "Absent",
}


def render() -> str:
    a = load_analysis()
    total = a["total_records"]
    detail = a["clause_prevalence"]["findings_detail_levels"]
    impact = a["clause_prevalence"]["impact_categories"]

    # Build detail rows
    detail_rows = []
    for key in DETAIL_ORDER:
        count = detail.get(key, 0)
        pct = (count / total) * 100 if total else 0.0
        detail_rows.append(
            f"{DETAIL_LABELS[key]:<8} & {count:>2} & {pct:>4.1f}\\% \\\\"
        )

    # Build impact rows sorted by count desc
    impact_sorted = sorted(impact.items(), key=lambda x: -x[1])
    impact_rows = []
    for key, count in impact_sorted:
        label = IMPACT_LABELS.get(key, key.replace("_", " ").title())
        pct = (count / total) * 100 if total else 0.0
        impact_rows.append(
            f"{label:<22} & {count:>2} & {pct:>4.1f}\\% \\\\"
        )

    detail_body = "\n".join(detail_rows)
    impact_body = "\n".join(impact_rows)

    return f"""% Auto-generated by scripts/generate_tables/findings_impact.py
% Source: research/analysis/moratorium-analysis.json
\\begin{{table}}[htbp]
\\centering
\\caption{{Legislative Findings: Detail Levels and Impact Categories}}
\\label{{tab:findings-impact}}

\\begin{{subtable}}[t]{{0.40\\textwidth}}
\\centering
\\caption{{Findings Detail Level}}
\\label{{tab:findings-detail}}
\\begin{{tabular}}{{lrr}}
\\toprule
Detail Level & Count & \\% \\\\
\\midrule
{detail_body}
\\midrule
\\textit{{Total}} & \\textit{{{total}}} & \\textit{{100.0\\%}} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{subtable}}%
\\hfill
\\begin{{subtable}}[t]{{0.55\\textwidth}}
\\centering
\\caption{{Impact Categories Cited in Findings}}
\\label{{tab:impact-categories}}
\\begin{{tabular}}{{lrr}}
\\toprule
Impact Category & Count & \\% \\\\
\\midrule
{impact_body}
\\bottomrule
\\end{{tabular}}
\\end{{subtable}}

\\begin{{flushleft}}
\\small\\textit{{Note:}} Based on $n = {total}$ structured extractions.
Percentages reflect the share of instruments. Multiple impact categories
may be cited in the same instrument, so the impact-categories column does
not sum to 100\\%.
\\end{{flushleft}}
\\end{{table}}
"""


def main():
    out = TABLES_DIR / "findings-impact.tex"
    out.write_text(render())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
