"""Generate latex/tables/moratorium-inventory-clean.tex from the inventory CSV.

This is the curated longtable that appears in Appendix A. We emit one row
per cleaned-inventory entry, sorted by state then jurisdiction. Date is
truncated to YYYY-MM, duration is normalized via _common.normalize_duration,
sector is the union of detected sectors, instrument form is heuristically
inferred from legal_basis, and status is derived from current_status text.

The hand-curated annotations (per-row footnotes about specific bills) are
NOT preserved here — they live in `latex/tables/inventory-annotations.tex`
if needed and are conditionally inputted from this longtable. For now we
keep this generator vanilla; targeted annotations can be reapplied as
sed-style overlays after generation.
"""

from __future__ import annotations

import re
from pathlib import Path

from ._common import (
    TABLES_DIR,
    cleaned_inventory,
    classify_all_sectors,
    latex_escape,
    load_inventory,
    normalize_duration,
    parse_year_month,
)


def infer_form(row) -> str:
    """Heuristically classify the instrument form from legal_basis."""
    s = (row.legal_basis or "").lower()
    if "ordinance" in s:
        return "Ordinance"
    if "resolution" in s:
        return "Resolution"
    if "regulation" in s or "land use code" in s or "zoning" in s:
        return "Regulation"
    if "bill" in s or "act" in s or "hb" in s or "sb" in s:
        return "Bill"
    if "motion" in s:
        return "Motion"
    return "Other"


STATUS_PATTERNS = [
    ("Replaced", re.compile(r"replaced|superseded|permanent ordinance", re.I)),
    ("Rescinded", re.compile(r"rescinded|repealed|withdrawn", re.I)),
    ("Expired", re.compile(r"expired|lapsed", re.I)),
    ("Extended", re.compile(r"extended|extension", re.I)),
    ("Pending", re.compile(r"pending|proposed|first reading|not yet enacted|public hearing", re.I)),
    ("Active", re.compile(r"active|in effect|in force", re.I)),
]


def infer_status(row) -> str:
    text = f"{row.current_status} {row.outcome}"
    for label, pat in STATUS_PATTERNS:
        if pat.search(text):
            return label
    return "Active" if text.strip() else "—"


def short_date(row) -> str:
    ym = parse_year_month(row.date_enacted)
    if ym:
        return ym
    if not row.date_enacted or row.date_enacted.lower() in {"none", "n/a", ""}:
        return "---"
    return "---"


def render() -> str:
    rows = cleaned_inventory(load_inventory())

    # Group by state for the section comments
    state_chunks: dict[str, list] = {}
    for r in rows:
        state_chunks.setdefault(r.state, []).append(r)
    body = []
    last_state = None
    for r in rows:
        if r.state != last_state:
            body.append(f"%% {r.state}")
            last_state = r.state
        sectors = classify_all_sectors(r)
        sector_str = ", ".join(sectors[:3])
        body.append(
            " & ".join([
                latex_escape(r.jurisdiction),
                r.state_abbrev,
                short_date(r),
                normalize_duration(r.duration),
                latex_escape(sector_str),
                infer_form(r),
                infer_status(r),
            ]) + " \\\\"
        )

    body_text = "\n".join(body)

    return f"""% Auto-generated by scripts/generate_tables/inventory_clean.py
% Source: research/analysis/moratorium_inventory.csv
% Cleaned: governmental rows only, sorted by state then jurisdiction.
{{\\footnotesize
\\setlength{{\\tabcolsep}}{{3.5pt}}
\\renewcommand{{\\arraystretch}}{{1.15}}
\\begin{{longtable}}{{lllllll}}
\\caption{{Inventory of Infrastructure Moratoria in the United States}} \\label{{tab:moratorium-inventory}} \\\\
\\toprule
Jurisdiction & State & Date & Duration & Sector & Form & Status \\\\
\\midrule
\\endfirsthead
\\multicolumn{{7}}{{c}}{{\\tablename\\ \\thetable{{}} -- continued}} \\\\
\\toprule
Jurisdiction & State & Date & Duration & Sector & Form & Status \\\\
\\midrule
\\endhead
\\noalign{{\\vskip 2pt}}
\\multicolumn{{7}}{{r}}{{\\textit{{Continued on next page}}}} \\\\
\\endfoot
\\bottomrule
\\multicolumn{{7}}{{l}}{{\\footnotesize\\textit{{Source:}} Author's compilation from municipal records, state legislation, and public documents.}} \\\\
\\multicolumn{{7}}{{l}}{{\\footnotesize Data current through April 2026.}} \\\\
\\endlastfoot
{body_text}
\\end{{longtable}}
}}
"""


def main():
    out = TABLES_DIR / "moratorium-inventory-clean.tex"
    out.write_text(render())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
