"""Generate latex/tables/sector-specific-clauses.tex from moratorium-analysis.json.

Plain table listing each sector-specific provision in the taxonomy, sorted
by prevalence. Percentages from analysis_json.clause_prevalence.sector_specific_clauses.
"""

from __future__ import annotations

from ._common import TABLES_DIR, load_analysis


LABELS = {
    "has_water_assessment": "Water Resource Assessment",
    "has_grid_assessment": "Grid/Energy Impact Assessment",
    "has_incentive_guardrails": "Incentive Guardrails",
    "has_noise_generator_provisions": "Noise/Generator Provisions",
    "has_fire_safety": "Fire Safety Requirements",
    "has_decommissioning_bond": "Decommissioning Bond",
    "has_hazmat_training": "Hazmat Training",
    "has_farmland_preservation": "Farmland Preservation",
    "has_safety_incident_trigger": "Safety Incident Trigger",
    "has_property_value_guarantee": "Property Value Guarantee",
    "has_physical_hazard_assessment": "Physical Hazard Assessment",
    "has_aviation_clearance": "Aviation Clearance",
}


def render() -> str:
    a = load_analysis()
    total = a["total_records"]
    clauses = a["clause_prevalence"].get("sector_specific_clauses", {})

    items = []
    for key, label in LABELS.items():
        entry = clauses.get(key, {})
        count = entry.get("count", 0)
        pct = entry.get("pct")
        if pct is None:
            pct = (count / total) * 100 if total else 0.0
        items.append((label, count, pct))

    # Sort by count descending, stable
    items.sort(key=lambda x: -x[1])

    body = "\n".join(
        f"{label:<29} & {count} & {pct:.1f}\\% \\\\"
        for label, count, pct in items
    )

    return f"""% Auto-generated by scripts/generate_tables/sector_specific_clauses.py
% Source: research/analysis/moratorium-analysis.json
\\begin{{table}}[htbp]
\\centering
\\caption{{Sector-Specific Clause Prevalence in Moratorium Instruments}}
\\label{{tab:sector-specific-clauses}}
\\begin{{tabular}}{{lrr}}
\\toprule
Provision & Count & \\% \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\begin{{flushleft}}
\\small\\textit{{Note:}} Percentages are based on {total} total moratorium
instruments. Provisions with zero prevalence represent categories from the
extraction taxonomy that were not present in any instrument in the dataset.
\\end{{flushleft}}
\\end{{table}}
"""


def main():
    out = TABLES_DIR / "sector-specific-clauses.tex"
    out.write_text(render())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
