"""Generate latex/tables/state-sector-counts.tex from the moratorium inventory.

Cross-tab of states (with three or more instruments) by sector. Each row
counts every sector mentioned in the row using the same heuristics as
src/moratorium_maps/maps.py::map_sector_composition. The Total column
counts unique instruments (so multi-sector rows aren't double-counted in
the row total).
"""

from __future__ import annotations

from collections import Counter, defaultdict

from ._common import (
    SECTORS,
    TABLES_DIR,
    classify_all_sectors,
    cleaned_inventory,
    load_inventory,
)

# Always render in this order
COLS = ["Data Center", "Crypto", "BESS", "Solar", "Wind", "Other"]


def render(min_total: int = 3) -> str:
    rows = cleaned_inventory(load_inventory())

    # state -> sector -> count
    matrix: dict[str, Counter] = defaultdict(Counter)
    state_totals: Counter = Counter()
    for r in rows:
        if not r.state:
            continue
        sectors = classify_all_sectors(r)
        # Single primary "Other" if we cannot classify
        if not sectors:
            sectors = ["Other"]
        for s in sectors:
            matrix[r.state][s] += 1
        state_totals[r.state] += 1

    qualified = [(s, t) for s, t in state_totals.most_common() if t >= min_total]
    if not qualified:
        raise SystemExit("No states meet the minimum-total threshold")

    body_lines = []
    subtotal = Counter()
    subtotal_total = 0
    for state, total in qualified:
        cells = []
        for col in COLS:
            cells.append(str(matrix[state].get(col, 0)))
            subtotal[col] += matrix[state].get(col, 0)
        body_lines.append(
            f"{state:<14} & " + " & ".join(f"{c:>2}" for c in cells)
            + f" & {total:>2} \\\\"
        )
        subtotal_total += total

    n_qualified = len(qualified)
    remaining_states = len([s for s, t in state_totals.items() if t < min_total])
    remaining_count = sum(t for s, t in state_totals.items() if t < min_total)

    subtotal_cells = " & ".join(f"\\textit{{{subtotal[c]}}}" for c in COLS)
    subtotal_line = (
        f"\\textit{{Subtotal ({n_qualified} states)}} & "
        f"{subtotal_cells} & \\textit{{{subtotal_total}}} \\\\"
    )

    body = "\n".join(body_lines)

    return f"""% Auto-generated by scripts/generate_tables/state_sector_counts.py
% Source: research/analysis/moratorium_inventory.csv
\\begin{{table}}[tp]
\\centering
\\caption{{Moratorium Count by State and Sector (States with Three or More)}}
\\label{{tab:state-sector-counts}}
\\begin{{tabular}}{{lrrrrrr r}}
\\toprule
State & Data Ctr. & Crypto & BESS & Solar & Wind & Other & Total \\\\
\\midrule
{body}
\\midrule
{subtotal_line}
\\bottomrule
\\end{{tabular}}
\\begin{{flushleft}}
\\small\\textit{{Note:}} Sector columns reflect the number of instruments mentioning each sector
in the cleaned inventory (\\Cref{{app:inventory}}, $n = {len(rows)}$).
Individual instruments may cover multiple sectors, so row totals reflect
instrument counts rather than the sum of sector columns.
``Other'' includes general industrial moratoria.
The remaining {remaining_states} states ({remaining_count} instruments) each contribute one or two entries.
\\end{{flushleft}}
\\end{{table}}
"""


def main():
    out = TABLES_DIR / "state-sector-counts.tex"
    out.write_text(render())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
