"""Generate latex/tables/temporal-distribution.tex from the moratorium inventory.

Produces a vertical pgfplots bar chart of moratorium adoption counts by year.
Years with at least one instrument are emitted; ymax is rounded up to a clean
multiple of 5.
"""

from __future__ import annotations

from collections import Counter

from ._common import (
    TABLES_DIR,
    cleaned_inventory,
    load_inventory,
    parse_year,
)


def render() -> str:
    rows = cleaned_inventory(load_inventory())
    years = Counter()
    dated = 0
    for r in rows:
        y = parse_year(r.date_enacted)
        if y is None:
            continue
        years[y] += 1
        dated += 1
    if not years:
        raise SystemExit("No dated rows found in inventory")
    ordered = sorted(years.items())
    coords = " ".join(f"({y},{c})" for y, c in ordered)
    year_csv = ",".join(str(y) for y, _ in ordered)
    ymax = ((max(years.values()) // 5) + 1) * 5
    excluded = len(rows) - dated

    return f"""% Auto-generated by scripts/generate_tables/temporal_distribution.py
% Source: research/analysis/moratorium_inventory.csv
\\begin{{figure}}[tp]
\\centering
\\caption{{Temporal Distribution of Moratorium Enactments}}
\\label{{tab:temporal-distribution}}
\\begin{{tikzpicture}}
\\begin{{axis}}[
    ybar,
    bar width=18pt,
    width=0.82\\textwidth,
    height=5.5cm,
    ylabel={{Number of Instruments}},
    xlabel={{Year}},
    symbolic x coords={{{year_csv}}},
    xtick=data,
    ymin=0,
    ymax={ymax},
    nodes near coords,
    nodes near coords style={{font=\\small\\bfseries, color=black}},
    every axis plot/.append style={{fill=chart-bar, draw=chart-bar-dark}},
    axis lines*=left,
    ymajorgrids=true,
    grid style={{gray!20}},
    tick label style={{font=\\small}},
    label style={{font=\\small}},
]
\\addplot[fill=chart-bar, draw=chart-bar-dark] coordinates {{
    {coords}
}};
\\end{{axis}}
\\end{{tikzpicture}}
\\begin{{flushleft}}
\\small\\textit{{Note:}} Counts reflect instruments with a recorded adoption date
in the cleaned inventory (\\Cref{{app:inventory}}, $n = {len(rows)}$).
{excluded} instrument{'s' if excluded != 1 else ''} lacked a parseable adoption
date and {'are' if excluded != 1 else 'is'} excluded.
\\end{{flushleft}}
\\end{{figure}}
"""


def main():
    out = TABLES_DIR / "temporal-distribution.tex"
    out.write_text(render())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
