"""Generate latex/tables/top-states.tex from the moratorium inventory.

Produces a horizontal pgfplots bar chart of states with the most instruments.
By default emits the top 12 states (matching the published draft); the `--top`
flag overrides.
"""

from __future__ import annotations

import argparse
from collections import Counter

from ._common import (
    TABLES_DIR,
    cleaned_inventory,
    load_inventory,
)


def render(top_n: int = 12) -> str:
    rows = cleaned_inventory(load_inventory())
    counts = Counter(r.state for r in rows if r.state)
    top = counts.most_common(top_n)
    if not top:
        raise SystemExit("No inventory rows found")
    # pgfplots wants y axis in display order. We list bottom-to-top.
    bottom_to_top = list(reversed(top))
    states = [s for s, _ in bottom_to_top]
    coords = " ".join(f"({c},{s})" for s, c in bottom_to_top)
    max_count = max(counts.values())
    xmax = ((max_count // 5) + 1) * 5  # round up to next multiple of 5

    states_csv = ",\n        ".join(states)
    return f"""% Auto-generated by scripts/generate_tables/top_states.py
% Source: research/analysis/moratorium_inventory.csv
\\begin{{figure}}[tp]
\\centering
\\caption{{Top States by Moratorium Count}}
\\label{{tab:top-states}}
\\begin{{tikzpicture}}
\\begin{{axis}}[
    xbar,
    bar width=10pt,
    width=0.78\\textwidth,
    height=6.5cm,
    xlabel={{Number of Instruments}},
    xmin=0,
    xmax={xmax},
    ytick=data,
    symbolic y coords={{
        {states_csv}
    }},
    nodes near coords,
    nodes near coords style={{font=\\small\\bfseries, anchor=west, color=black}},
    every axis plot/.append style={{fill=chart-bar, draw=chart-bar-dark}},
    axis lines*=left,
    xmajorgrids=true,
    grid style={{gray!20}},
    tick label style={{font=\\small}},
    label style={{font=\\small}},
    y dir=normal,
]
\\addplot[fill=chart-bar, draw=chart-bar-dark] coordinates {{
    {coords}
}};
\\end{{axis}}
\\end{{tikzpicture}}
\\begin{{flushleft}}
\\small\\textit{{Note:}} Counts reflect individual instruments in the cleaned
inventory (\\Cref{{app:inventory}}, $n = {len(rows)}$). Each entry represents a unique
jurisdiction--instrument pair after removing federal entities, non-governmental
actors, and duplicate extensions of the same underlying moratorium.
\\end{{flushleft}}
\\end{{figure}}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", type=int, default=12, help="Number of states to plot")
    parser.add_argument("--out", default=str(TABLES_DIR / "top-states.tex"))
    args = parser.parse_args()
    text = render(top_n=args.top)
    out = TABLES_DIR / "top-states.tex"
    out.write_text(text)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
