#!/usr/bin/env python3
"""Refresh the number-bearing parts of index.html from the shipped data.

index.html is the GitHub Pages landing page -- the most public-facing artifact in
this repository -- and until now it had no generator. Its headline counts were
hand-maintained, so they silently kept saying 222 while the inventory grew.

This does NOT regenerate the page. The layout and copy are hand-tuned and worth
keeping; rewriting them from a template would lose that. Instead it performs
anchored replacements on exactly the spans that state a number, leaving
everything else byte-identical. Anything it cannot locate is reported rather
than guessed at, the same discipline as scripts/check_docs_numbers.py.

Run from repo root:
    python3 scripts/build_index.py --check   # report drift, exit 1 if any
    python3 scripts/build_index.py           # apply
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
INDEX = REPO / "index.html"
INV = REPO / "data" / "moratorium_inventory.csv"
LEG = REPO / "data" / "state_legislation.csv"
SWEEP = REPO / "data" / "sweep_coverage.json"

VERIFY_RE = re.compile(r"\[VERIFY", re.IGNORECASE)

# Human-facing label for the current release; bump with the release.
RELEASE_LABEL = "July 2026"

SLUG = {
    "District of Columbia": "district-of-columbia",
}


def slug_for(state: str) -> str:
    return SLUG.get(state, state.lower().replace(" ", "-"))


def facts() -> dict:
    with open(INV, encoding="utf-8", newline="") as f:
        inv = list(csv.DictReader(f))
    with open(LEG, encoding="utf-8", newline="") as f:
        leg = list(csv.DictReader(f))
    c = Counter(r["enacted_status"] for r in inv)
    by_state = Counter(r["state"] for r in inv)
    swept = []
    if SWEEP.exists():
        w = json.loads(SWEEP.read_text(encoding="utf-8")).get("windows", [])
        if w:
            swept = w[-1].get("swept_states", [])
    # Clause-taxonomy cohort: reported alongside the inventory on the landing
    # page, and easy to mistake for a subset of it. Derive both numbers so the
    # caveat sentence stays true.
    cohort, cohort_j = 0, 0
    analysis = REPO / "data" / "clause_extraction_analysis.json"
    if analysis.exists():
        a = json.loads(analysis.read_text(encoding="utf-8"))
        cohort = a.get("total_records", 0)
        cohort_j = a.get("geographic", {}).get("total_unique_jurisdictions", 0)

    import datetime as _dt
    def _d(v):
        v=(v or "").strip()
        for fmt in ("%Y-%m-%d","%Y-%m","%Y"):
            try: return _dt.datetime.strptime(v, fmt).date()
            except ValueError: pass
        return None
    window_adoptions = sum(
        1 for r in inv
        if (x := _d(r["date_enacted_iso"])) and _dt.date(2026,5,1) <= x <= _dt.date(2026,7,31)
    )

    return {
        "rows": len(inv),
        "window_adoptions": window_adoptions,
        "fl_rows": by_state.get("Florida", 0),
        "bills_enacted": sum(1 for r in leg if r.get("bill_status_category") == "enacted"),
        "cohort": cohort,
        "cohort_jurisdictions": cohort_j,
        "in_force": c["active"] + c["extended"],
        "pending": c["pending"],
        "past": c["replaced"] + c["expired"] + c["rescinded"],
        "states": len(by_state),
        "geocoded": sum(1 for r in inv if r["latitude"].strip()),
        "bills": len(leg),
        "top": by_state.most_common(13),
        "swept_count": len(swept),
    }


def top_states_block(top: list[tuple[str, int]]) -> str:
    rows = [
        f'    <div class="row"><a href="states/{slug_for(s)}.html">'
        f"<strong>{s}</strong></a><strong>{n}</strong></div>"
        for s, n in top
    ]
    return "\n".join(rows)


CHANGES_START = "<!-- BEGIN whats-changed (generated by scripts/build_index.py) -->"
CHANGES_END = "<!-- END whats-changed -->"


def changes_section(f: dict) -> str:
    """The 'what changed since April' block.

    Delimited by HTML comments so it can be regenerated in place without
    disturbing the surrounding hand-written page.
    """
    return f"""{CHANGES_START}
<section>
  <h2>What changed between the April and July 2026 updates</h2>
  <p>The inventory grew from <strong>222</strong> to <strong>{f['rows']}</strong> instruments and from
  <strong>30</strong> to <strong>{f['states']}</strong> states. Most of that growth is <em>coverage</em>, not a sudden
  surge: this release was the first to sweep states month by month rather than
  opportunistically. Read {f['rows']} as a floor, not a count.</p>

  <h3>New activity</h3>
  <ul>
    <li><strong>{f['window_adoptions']} instruments were adopted between 2026-05-01 and 2026-07-31.</strong>
      June was the single busiest month we have recorded.</li>
    <li><strong>Large cities entered the pattern.</strong> Seattle (emergency ordinance, June 9),
      Cleveland (14-1, July 15), Minneapolis, Denver, Charlotte, and Montgomery County, MD
      (18-month pause plus a hyperscale ban, July 28). Durham city and Durham county each
      adopted their own.</li>
    <li><strong>Five states entered the dataset for the first time:</strong> Florida, Nevada,
      New Mexico, South Carolina, and Texas.</li>
  </ul>

  <h3>What happened to existing moratoria</h3>
  <ul>
    <li><strong>Extensions were the most common outcome.</strong> DeKalb County, GA voted its
      permanent ordinance down and instead extended its pause to March 2027; Prince George's
      County, MD renewed for two more years.</li>
    <li><strong>Nine converted into permanent regulations</strong> - among them Griffin and Polk
      County, GA; Montour County, PA; Brevard, NC; and St. Charles Parish, LA.</li>
    <li><strong>Six lapsed with nothing adopted</strong>, including La Grange, KY and Waterville, OH.</li>
    <li><strong>A few were defeated or undone.</strong> Lowell Township, MI rejected a moratorium 2-5;
      Hill County, TX rescinded one after a $100M developer lawsuit; Oliver County, ND repealed
      its third-phase moratorium seven weeks in.</li>
  </ul>

  <h3>State legislation</h3>
  <p>All <strong>{f['bills']}</strong> tracked bills now carry a researched final disposition, and
  <strong>{f['bills_enacted']}</strong> are enacted. The 2026 session converged on
  <em>ratepayer protection and cost allocation</em> rather than outright bans - New Jersey's
  large-load tariff act (signed July 7), Oklahoma's Data Center Customer Protection Act,
  Maryland's Utility RELIEF Act, and Idaho's 50 MW "no harm" test. Florida cut the other way,
  preserving local land-use authority over large-load customers.</p>

  <h3>How to read the coverage</h3>
  <p>{f['swept_count']} states were swept systematically for May through July; the remaining
  {50 - f['swept_count']} were not, and their counts for that window are lower bounds. Florida held one row
  before its sweep was converted and {f['fl_rows']} after - the state did not change, only our looking did.
  Five swept states genuinely recorded no local adoptions in the window, which is a finding
  rather than a gap. See <a href="docs/known-gaps.html">known gaps</a> for the full accounting.</p>
</section>
{CHANGES_END}"""


def build_edits(f: dict) -> list[tuple[str, str, str]]:
    """(label, regex, replacement). Each regex must match exactly once."""
    top_n = len(f["top"])
    share = round(sum(n for _, n in f["top"]) * 100 / f["rows"])
    return [
        ("meta description",
         r'(<meta name="description" content="Open data and a 116-page working paper on )\d+( local-government moratoria)',
         rf"\g<1>{f['rows']}\g<2>"),
        ("meta description date",
         r'(cryptocurrency mining across the United States\. Updated )[A-Z][a-z]+ \d{4}(\.")',
         rf"\g<1>{RELEASE_LABEL}\g<2>"),
        ("og:description",
         r'(<meta property="og:description" content=")\d+( moratoria across )\d+( states)',
         rf"\g<1>{f['rows']}\g<2>{f['states']}\g<3>"),
        ("subtitle date",
         r'(across the United States\. Updated )[A-Z][a-z]+ \d{4}(\.</p>)',
         rf"\g<1>{RELEASE_LABEL}\g<2>"),
        ("stat-total",
         r'(<div class="num" id="stat-total">)\d+(</div>)',
         rf"\g<1>{f['rows']}\g<2>"),
        ("stat-in-force",
         r'(<div class="num" id="stat-in-force">)\d+(</div>)',
         rf"\g<1>{f['in_force']}\g<2>"),
        ("stat-pending",
         r'(<div class="num" id="stat-pending">)\d+(</div>)',
         rf"\g<1>{f['pending']}\g<2>"),
        ("stat-past",
         r'(<div class="num" id="stat-past">)\d+(</div>)',
         rf"\g<1>{f['past']}\g<2>"),
        # This tile carries no id, so anchor on its label instead.
        ("stat-states",
         r'(<div class="num">)\d+(</div>\s*\n\s*<div class="label">States with at least one</div>)',
         rf"\g<1>{f['states']}\g<2>"),
        ("map caption",
         r"(Map shows )\d+( of )\d+( instruments\.)",
         rf"\g<1>{f['geocoded']}\g<2>{f['rows']}\g<3>"),
        ("top-states heading",
         r"(<h2>Top )\d+( states by moratorium count</h2>)",
         rf"\g<1>{top_n}\g<2>"),
        # Matches both the original hand-written phrasing ("more than four-fifths")
        # and this script's own output, so re-running is a no-op.
        ("top-states lead",
         r"These (?:\w+|\d+) states account for (?:more than [\w-]+|about \d+ percent) of all identified instruments\.",
         f"These {top_n} states account for about {share} percent of all identified instruments."),
        ("top-states rows",
         r'(<div class="top-states">\n)(?:.*?\n)*?(  </div>)',
         lambda: top_states_block(f["top"]) + r"\n\g<2>"),
        ("all-states link",
         r"(All )\d+( states with moratoria)",
         rf"\g<1>{f['states']}\g<2>"),
        ("csv row count",
         r"(The )\d+(-row inventory as a CSV)",
         rf"\g<1>{f['rows']}\g<2>"),
        ("timeline alt text",
         r"(alt=\"Monthly moratorium adoptions, 2018 through )[A-Z][a-z]+ \d{4}(,)",
         rf"\g<1>{RELEASE_LABEL}\g<2>"),
        # The clause cohort is NOT the inventory -- it was collected before
        # 2026-04-28 and covers 211 jurisdictions. Stating that inline stops the
        # two numbers on this page being read as one.
        ("clause cohort caveat",
         r"\d+ moratorium texts have been read line-by-line and coded against a 44-clause taxonomy\.(?: This sample was collected[^.]*\.)?",
         f"{f['cohort']} moratorium texts have been read line-by-line and coded against a "
         f"44-clause taxonomy. This sample was collected before 2026-04-28 and covers "
         f"{f['cohort_jurisdictions']} jurisdictions, so it describes what moratoria contain "
         f"rather than all {f['rows']} instruments."),
    ]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report drift without writing")
    args = ap.parse_args()

    f = facts()
    html = INDEX.read_text(encoding="utf-8")
    original = html
    applied, missing = [], []

    # Insert or refresh the generated "what changed" section.
    block = changes_section(f)
    if CHANGES_START in html:
        start = html.index(CHANGES_START)
        end = html.index(CHANGES_END) + len(CHANGES_END)
        if html[start:end] != block:
            html = html[:start] + block + html[end:]
            applied.append("whats-changed section")
    else:
        anchor = '<div class="paper-callout">'
        if anchor in html:
            html = html.replace(anchor, block + "\n\n" + anchor, 1)
            applied.append("whats-changed section (inserted)")
        else:
            missing.append("whats-changed anchor")

    for label, pattern, repl in build_edits(f):
        if label == "top-states rows":
            m = re.search(r'(<div class="top-states">\n)((?:.*?\n)*?)(  </div>)', html)
            if not m:
                missing.append(label)
                continue
            new_block = m.group(1) + top_states_block(f["top"]) + "\n" + m.group(3)
            if m.group(0) != new_block:
                html = html[: m.start()] + new_block + html[m.end():]
                applied.append(label)
            continue
        new_html, n = re.subn(pattern, repl, html, count=1)
        if n == 0:
            missing.append(label)
        elif new_html != html:
            html = new_html
            applied.append(label)

    print(f"Data: {f['rows']} instruments, {f['in_force']} in force, {f['pending']} pending, "
          f"{f['states']} states, {f['geocoded']} geocoded, {f['bills']} bills")

    if missing:
        print(f"\n{len(missing)} anchor(s) NOT FOUND -- update the patterns in this script:")
        for label in missing:
            print(f"  {label}")

    if not applied:
        print("\nindex.html is already current.")
        return 1 if missing else 0

    if args.check:
        print(f"\nindex.html is OUT OF DATE -- {len(applied)} span(s) would change:")
        for label in applied:
            print(f"  {label}")
        return 1

    INDEX.write_text(html, encoding="utf-8")
    print(f"\nWrote index.html ({len(applied)} span(s) updated):")
    for label in applied:
        print(f"  {label}")
    print(f"  bytes {len(original)} -> {len(html)}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
