#!/usr/bin/env python3
"""Refresh the number-bearing parts of index.html from the shipped data.

index.html is the GitHub Pages landing page -- the most public-facing artifact in
this repository -- and until now it had no generator. Its headline counts were
hand-maintained, so they silently kept saying 222 while the inventory grew.

This does NOT regenerate the page. The layout and copy are hand-tuned and worth
keeping; rewriting them from a template would lose that. Instead it performs
anchored replacements on exactly the spans that state a number, leaving
everything else byte-identical. Anything it cannot locate is reported rather
than guessed at, the same discipline as scripts/check_docs_numbers.py.

Run from repo root:
    python3 scripts/build_index.py --check   # report drift, exit 1 if any
    python3 scripts/build_index.py           # apply
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
INDEX = REPO / "index.html"
INV = REPO / "data" / "moratorium_inventory.csv"
LEG = REPO / "data" / "state_legislation.csv"
SWEEP = REPO / "data" / "sweep_coverage.json"

VERIFY_RE = re.compile(r"\[VERIFY", re.IGNORECASE)

# Human-facing label for the current release; bump with the release.
RELEASE_LABEL = "July 2026"
RELEASE_DATE = "31 July 2026"

NUMBER_WORDS = {
    10: "Ten", 11: "Eleven", 12: "Twelve", 13: "Thirteen",
    14: "Fourteen", 15: "Fifteen",
}

SLUG = {
    "District of Columbia": "district-of-columbia",
}


def slug_for(state: str) -> str:
    return SLUG.get(state, state.lower().replace(" ", "-"))


def facts() -> dict:
    with open(INV, encoding="utf-8", newline="") as f:
        inv = list(csv.DictReader(f))
    with open(LEG, encoding="utf-8", newline="") as f:
        leg = list(csv.DictReader(f))
    c = Counter(r["enacted_status"] for r in inv)
    by_state = Counter(r["state"] for r in inv)
    swept = []
    if SWEEP.exists():
        w = json.loads(SWEEP.read_text(encoding="utf-8")).get("windows", [])
        if w:
            swept = w[-1].get("swept_states", [])
    # Clause-taxonomy cohort: reported alongside the inventory on the landing
    # page, and easy to mistake for a subset of it. Derive both numbers so the
    # caveat sentence stays true.
    cohort, cohort_j = 0, 0
    analysis = REPO / "data" / "clause_extraction_analysis.json"
    if analysis.exists():
        a = json.loads(analysis.read_text(encoding="utf-8"))
        cohort = a.get("total_records", 0)
        cohort_j = a.get("geographic", {}).get("total_unique_jurisdictions", 0)

    import datetime as _dt
    def _d(v):
        v=(v or "").strip()
        for fmt in ("%Y-%m-%d","%Y-%m","%Y"):
            try: return _dt.datetime.strptime(v, fmt).date()
            except ValueError: pass
        return None
    window_adoptions = sum(
        1 for r in inv
        if (x := _d(r["date_enacted_iso"])) and _dt.date(2026,5,1) <= x <= _dt.date(2026,7,31)
    )

    return {
        "rows": len(inv),
        "window_adoptions": window_adoptions,
        "dated": sum(1 for r in inv if _d(r["date_enacted_iso"])),
        # The chart bins by month, so a year-only date cannot be plotted.
        "plotted": sum(
            1 for r in inv
            if len((r["date_enacted_iso"] or "")[:7]) == 7 and (r["date_enacted_iso"] or "")[4:5] == "-"
        ),
        "fl_rows": by_state.get("Florida", 0),
        "bills_enacted": sum(1 for r in leg if r.get("bill_status_category") == "enacted"),
        "cohort": cohort,
        "cohort_jurisdictions": cohort_j,
        "in_force": c["active"] + c["extended"],
        "pending": c["pending"],
        "past": c["replaced"] + c["expired"] + c["rescinded"],
        "states": len(by_state),
        "geocoded": sum(1 for r in inv if r["latitude"].strip()),
        "bills": len(leg),
        "top": by_state.most_common(13),
        "swept_count": len(swept),
    }


def top_states_block(top: list[tuple[str, int]]) -> str:
    rows = [
        f'    <div class="row"><a href="states/{slug_for(s)}.html">'
        f"<strong>{s}</strong></a><strong>{n}</strong></div>"
        for s, n in top
    ]
    return "\n".join(rows)


CHANGES_START = "<!-- BEGIN whats-changed (generated by scripts/build_index.py) -->"
CHANGES_END = "<!-- END whats-changed -->"


def changes_section(f: dict) -> str:
    """The release-notes block.

    Delimited by HTML comments so it regenerates in place. Copy follows the
    house style in ../book-template/docs/guides/STYLE.md: front-loaded claims,
    active voice, varied sentence length, no filler transitions.
    """
    unswept = 50 - f["swept_count"]
    return f"""{CHANGES_START}
<section class="release-notes">
  <div class="stamp">Release v2026.07 &middot; 31 July 2026</div>
  <h2>What changed since April</h2>
  <p class="lede">The inventory grew from 222 instruments to {f['rows']}, across {f['states']} states
  instead of 30. Method explains most of that jump. This is the first release to sweep
  states month by month, so read {f['rows']} as a floor.</p>

  <h3>New activity</h3>
  <ul>
    <li><strong>{f['window_adoptions']} moratoria were adopted between May 1 and July 31.</strong>
      June accounted for 80 of them, the busiest month on record.</li>
    <li><strong>Big cities joined in.</strong> Seattle passed an emergency ordinance on June 9.
      Cleveland followed on July 15 by a 14-1 vote, after committee cut the term from twelve
      months to three. Minneapolis, Denver, Charlotte, and Montgomery County, Maryland all
      acted. Durham city and Durham County each passed their own.</li>
    <li><strong>Five states appear here for the first time:</strong> Florida, Nevada, New Mexico,
      South Carolina, and Texas.</li>
  </ul>

  <h3>What happened to the older ones</h3>
  <ul>
    <li><strong>Extension is the usual outcome.</strong> DeKalb County, Georgia voted its permanent
      ordinance down on June 23, then pushed the pause out to March 2027. Prince George's
      County, Maryland renewed for two more years.</li>
    <li><strong>Nine became permanent rules</strong> - among them Griffin and Polk County in
      Georgia, Montour County in Pennsylvania, Brevard in North Carolina, and St. Charles
      Parish in Louisiana.</li>
    <li><strong>Six simply lapsed.</strong> La Grange, Kentucky and Waterville, Ohio let theirs
      run out with nothing ready to replace them.</li>
    <li><strong>A few went the other way.</strong> Lowell Township, Michigan voted a moratorium
      down 2-5. Hill County, Texas repealed one after a developer sued for $100 million.
      Oliver County, North Dakota repealed its third pause seven weeks in.</li>
  </ul>

  <h3>State legislation</h3>
  <p>All {f['bills']} tracked bills now carry a final disposition, and {f['bills_enacted']} are law.
  Legislatures went after cost allocation more than siting. New Jersey signed its large-load
  tariff act on July 7. Oklahoma passed a Data Center Customer Protection Act, Maryland the
  Utility RELIEF Act, and Idaho now requires a "no harm" test for any new load above 50
  megawatts. Florida moved the opposite way and protected local land-use authority.</p>

  <h3>How to read the coverage</h3>
  <p>{f['swept_count']} states got the month-by-month sweep. The other {unswept} did not, so their
  May-July counts are floors. Florida shows why: it held one row before its sweep and
  {f['fl_rows']} after. The state did not change. Our looking did. Five swept states recorded no
  local adoptions at all - a finding worth as much as a count.
  <a href="docs/known-gaps.html">Known gaps</a> has the full accounting.</p>
</section>
{CHANGES_END}"""


def build_edits(f: dict) -> list[tuple[str, str, str]]:
    """(label, regex, replacement). Each regex must match exactly once."""
    top_n = len(f["top"])
    share = round(sum(n for _, n in f["top"]) * 100 / f["rows"])
    # Prose reads better as a fraction than a percentage at this precision.
    share_phrase = (
        "four in five" if share >= 78 else
        "three in four" if share >= 72 else
        "two in three" if share >= 63 else
        f"{share} percent"
    )
    return [
        ("meta description",
         r'(<meta name="description" content="Open data and a 116-page working paper on )\d+( local-government moratoria)',
         rf"\g<1>{f['rows']}\g<2>"),
        ("meta description date",
         r'(cryptocurrency mining across the United States\. Updated )[A-Z][a-z]+ \d{4}(\.")',
         rf"\g<1>{RELEASE_LABEL}\g<2>"),
        ("og:description",
         r'(<meta property="og:description" content=")\d+( moratoria across )\d+( states)',
         rf"\g<1>{f['rows']}\g<2>{f['states']}\g<3>"),
        # The date lives in the hero eyebrow now, not the subtitle.
        ("hero eyebrow date",
         r'(<div class="eyebrow"><span class="dot"></span>Updated )[^<]*(</div>)',
         rf"\g<1>{RELEASE_DATE} &middot; v2026.07\g<2>"),
        ("stat-total",
         r'(<div class="num" id="stat-total">)\d+(</div>)',
         rf"\g<1>{f['rows']}\g<2>"),
        ("stat-in-force",
         r'(<div class="num" id="stat-in-force">)\d+(</div>)',
         rf"\g<1>{f['in_force']}\g<2>"),
        ("stat-pending",
         r'(<div class="num" id="stat-pending">)\d+(</div>)',
         rf"\g<1>{f['pending']}\g<2>"),
        ("stat-total delta",
         r'(<div class="num" id="stat-total">\d+</div>)(?:\s*<div class="delta">[^<]*</div>)?',
         rf'\g<1>\n    <div class="delta">was 222 in April</div>'),
        ("stat-past",
         r'(<div class="num" id="stat-past">)\d+(</div>)',
         rf"\g<1>{f['past']}\g<2>"),
        # This tile carries no id, so anchor on its label instead.
        ("stat-states",
         r'(<div class="num">)\d+(</div>\s*\n\s*<div class="label">States with at least one</div>)',
         rf"\g<1>{f['states']}\g<2>"),
        ("map caption",
         r"(Map shows )\d+( of )\d+( instruments\.)",
         rf"\g<1>{f['geocoded']}\g<2>{f['rows']}\g<3>"),
        ("top-states heading",
         r"(<h2>Top )\d+( states by moratorium count</h2>)",
         rf"\g<1>{top_n}\g<2>"),
        ("top-states lead",
         r"(?:These|Thirteen|\w+) states hold roughly [\w -]+ of the instruments we have found\.",
         f"{NUMBER_WORDS.get(top_n, str(top_n))} states hold roughly {share_phrase} of the "
         f"instruments we have found."),
        ("top-states rows",
         r'(<div class="top-states">\n)(?:.*?\n)*?(  </div>)',
         lambda: top_states_block(f["top"]) + r"\n\g<2>"),
        ("all-states link",
         r"(All )\d+( states with moratoria)",
         rf"\g<1>{f['states']}\g<2>"),
        ("csv row count",
         r"(The )\d+(-row inventory as a CSV)",
         rf"\g<1>{f['rows']}\g<2>"),
        ("timeline caption",
         r'<p class="caption">(?:A handful of Washington|Washington logged|Every bar before).*?(?:</p>\s*<p class="source">.*?</p>|</p>)',
         '<p class="caption">Every bar before 2022 is Washington. Cheap hydro power pulled crypto '
         'miners into the Columbia Basin, and ten Washington jurisdictions paused them in 2018. '
         'Then the map went quiet for four years. Data centers restarted it: 7 moratoria in 2023, '
         '6 in 2024, 59 in 2025, and 294 in the first seven months of 2026. June alone '
         'accounted for 80.</p>\n'
         '  <p class="source">Source: <a href="data/moratorium_inventory.csv" download>'
         'moratorium_inventory.csv</a>, columns <code>date_enacted_iso</code> and '
         f'<code>sectors</code>. The chart plots {f["plotted"]} of {f["rows"]} instruments. '
         'It leaves out proposals still awaiting a vote, which have no adoption date, and two '
         '2018 Washington ordinances known only to the year, which cannot be placed in a '
         'month.</p>'),
        ("timeline alt text",
         r"(alt=\"Monthly moratorium adoptions, 2018 through )[A-Z][a-z]+ \d{4}(,)",
         rf"\g<1>{RELEASE_LABEL}\g<2>"),
        # The clause cohort is NOT the inventory -- it was collected before
        # 2026-04-28 and covers 211 jurisdictions. Stating that inline stops the
        # two numbers on this page being read as one.
        ("clause cohort caveat",
         r"\d+ moratorium texts have been read line by line against a 44-clause taxonomy; that "
         r"sample predates 28 April 2026 and covers \d+ jurisdictions, so it describes what "
         r"moratoria contain rather than all \d+ of them\.",
         f"{f['cohort']} moratorium texts have been read line by line against a 44-clause "
         f"taxonomy; that sample predates 28 April 2026 and covers "
         f"{f['cohort_jurisdictions']} jurisdictions, so it describes what moratoria contain "
         f"rather than all {f['rows']} of them."),
        ("release version",
         r"(This release is <strong>)v[\d.]+(</strong>)",
         rf"\g<1>v2026.07\g<2>"),
    ]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report drift without writing")
    args = ap.parse_args()

    f = facts()
    html = INDEX.read_text(encoding="utf-8")
    original = html
    applied, missing = [], []

    # Insert or refresh the generated "what changed" section.
    block = changes_section(f)
    if CHANGES_START in html:
        start = html.index(CHANGES_START)
        end = html.index(CHANGES_END) + len(CHANGES_END)
        if html[start:end] != block:
            html = html[:start] + block + html[end:]
            applied.append("whats-changed section")
    else:
        anchor = '<main>'
        if anchor in html:
            html = html.replace(anchor, anchor + "\n\n" + block, 1)
            applied.append("whats-changed section (inserted)")
        else:
            missing.append("whats-changed anchor")

    for label, pattern, repl in build_edits(f):
        if label == "top-states rows":
            m = re.search(r'(<div class="top-states">\n)((?:.*?\n)*?)(  </div>)', html)
            if not m:
                missing.append(label)
                continue
            new_block = m.group(1) + top_states_block(f["top"]) + "\n" + m.group(3)
            if m.group(0) != new_block:
                html = html[: m.start()] + new_block + html[m.end():]
                applied.append(label)
            continue
        new_html, n = re.subn(pattern, repl, html, count=1)
        if n == 0:
            missing.append(label)
        elif new_html != html:
            html = new_html
            applied.append(label)

    print(f"Data: {f['rows']} instruments, {f['in_force']} in force, {f['pending']} pending, "
          f"{f['states']} states, {f['geocoded']} geocoded, {f['bills']} bills")

    if missing:
        print(f"\n{len(missing)} anchor(s) NOT FOUND -- update the patterns in this script:")
        for label in missing:
            print(f"  {label}")

    if not applied:
        print("\nindex.html is already current.")
        return 1 if missing else 0

    if args.check:
        print(f"\nindex.html is OUT OF DATE -- {len(applied)} span(s) would change:")
        for label in applied:
            print(f"  {label}")
        return 1

    INDEX.write_text(html, encoding="utf-8")
    print(f"\nWrote index.html ({len(applied)} span(s) updated):")
    for label in applied:
        print(f"  {label}")
    print(f"  bytes {len(original)} -> {len(html)}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
